# Generated by Django 5.1.1 on 2024-10-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_message_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
