# Generated by Django 5.1.3 on 2024-11-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_message_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrequest',
            old_name='item_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home'), ('books', 'Books'), ('sports', 'Sports')], default='new', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
