# Generated by Django 5.1.3 on 2024-11-30 22:10

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_item_name_itemrequest_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.request_directory_path),
        ),
    ]
