# Generated by Django 5.1.3 on 2024-12-02 02:10

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_itemrequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=home.models.request_directory_path),
        ),
    ]
