# Generated by Django 5.1.3 on 2024-12-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_profile_city_profile_country_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
